Hellish challenge
mate-academy/js_task-inifinite-sum-closures pull request #801
Opened 2022-09-22 12:25 UTC by Vladosik1337

2022-09-23 09:55 UTC, jojnajbude approved these changes

2022-09-25 09:22 UTC, Anna-Tkachenko requested changes

2022-09-25 09:22 UTC, Anna-Tkachenko commented on src/makeInfinityAdder.js
> +    }
else is redundant after return statement

2022-09-26 06:57 UTC, Denchepornyuk approved these changes

2025-11-08 12:39 UTC, closed without merging